[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "16"

[build]
  publish = "dist/build/h5"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build:h5"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
