name: 让我逮到 Bug 了！
description: 创建一个 Issue 描述你遇到的问题
labels: [bug：需要确认]
title: '[Bug 上报] 请在此填写标题'
body:
  - type: markdown
    attributes:
      value: |
        在向我们提交 Bug 报告前，请优先使用以下方式尝试解决问题：
        - 尝试在 [Issue](https://github.com/Chadwuo/li-ji-weapp/issues) 列表中搜索相同问题
        - 如果不是反馈 Bug，请到 [Discussions 讨论区](https://github.com/Chadwuo/li-ji-weapp/discussions) 发帖。

  - type: textarea
    id: reproduce-steps
    attributes:
      label: 🔄 重现步骤
      description: 请提供一个最简洁清晰的重现步骤，方便我们快速重现问题。
      placeholder: |
        1. 打开小程序
        2. 点击 '...'
        3. 输入 '....'
        4. 点击 '....'
        5. 看到错误信息
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✨ 期望的结果是什么？

  - type: textarea
    id: actually-happening
    attributes:
      label: 💥 实际的结果是什么？

  - type: textarea
    id: environment
    attributes:
      label: 🌍 环境信息
      placeholder: |
        - 发行平台: [如 微信小程序、H5平台、App等]
        - 操作系统: [如 iOS 12.1.2、Android 7.0]
        - 设备信息: [如 iPhone8 Plus]
        - 相关版本信息: [如 HBuilderX 版本、uni-app版本等]

  - type: textarea
    id: extra
    attributes:
      label: 📝 其他补充信息
      description: |
        任何其他你认为有帮助的信息，比如：
        - 屏幕截图
        - 控制台错误信息
        - 你已经尝试过的解决方法
