name: 我想要个新功能
description: 创建一个 Issue 描述一下你的功能需求
labels: ['feature: need confirm']
title: '[新功能需求] 请在此填写标题'
body:
  - type: markdown
    attributes:
      value: |
        在提交功能需求前，请注意：
        - 确认这是一个通用功能。
        - 请确保描述清楚你的需求，以便其他开发者更好地理解你的需求。
        - 尝试在 [Issue](https://github.com/Chadwuo/li-ji-weapp/issues)列表中搜索，并且没有发现同样的需求。
        - 可以先到 [Discussions 讨论区](https://github.com/Chadwuo/li-ji-weapp/discussions) 发帖，讨论一下需求是否合理。

  - type: textarea
    id: description
    attributes:
      label: 🎯 这个功能解决了什么问题？
      description: 请尽可能详细地说明这个功能的使用场景。
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 💡 你期望的解决方案是什么？
      description: 描述一下你希望如何实现这个功能。

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 其他补充信息
      description: |
        任何其他你认为有帮助的信息，比如：
        - 类似的开源项目参考
        - 屏幕截图或设计图
        - 你已经尝试过的替代方案
