/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/book/page" |
       "/pages/about/index" |
       "/pages/book/detail" |
       "/pages/book/edit" |
       "/pages/exception/500" |
       "/pages/family/index" |
       "/pages/family/invite" |
       "/pages/faq/index" |
       "/pages/friend/detail" |
       "/pages/friend/edit" |
       "/pages/friend/list" |
       "/pages/giftIn/edit" |
       "/pages/giftOut/edit" |
       "/pages/giftOut/page" |
       "/pages/mine/index" |
       "/pages/settings/index" |
       "/pages/sponsor/index";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
